[package]
name = "shogi_official_kifu"
version = "0.1.0"
edition = "2021"

[features]
default = ["kansuji", "std"]
kansuji = []
std = []

[lib]
crate-type = [
    "rlib",
    "cdylib",
]

[dependencies]
shogi = "0.12"

[profile.dev]
debug = false

[profile.release]
opt-level = "z"
strip = "symbols"

[profile.release-cargo-bloat]
inherits = "release"
strip = "debuginfo" # "symbols" prevents cargo-bloat from displaying crate-wise info.
