name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  RUSTDOCFLAGS: --deny warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo version
      run: cargo --version
    - name: install nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --locked --all-features
    - name: Run clippy
      run: cargo clippy --all-targets --locked
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Build (various features)
      run: |
        cargo +nightly build --verbose --no-default-features
        cargo build --verbose --no-default-features --features std
        cargo +nightly build --verbose --no-default-features --features kansuji
        cargo build --verbose --all-features
    - name: Document
      run: cargo doc --verbose --all-features
